---

- name: Setup TMUX facts
  set_fact:
    tmux_dir: '{{ config_directory }}/tmux'

- name: Create TMUX Config directory
  file:
    path: '{{ tmux_dir }}'
    state: directory

- name: Copy TMUX Config file
  copy:
    src: 'files/tmux.conf'
    dest: '{{ tmux_dir }}/tmux.conf'

- name: Create TMUX Scripts directory
  file:
    path: '{{ tmux_dir }}/scripts'
    state: directory

- name: Copy TMUX Git Script
  copy:
    src: 'files/git-branch.sh'
    dest: '{{ tmux_dir }}/scripts/git-branch.sh'
    mode: '0744'

- name: Symlink tmux scripts
  file:
    src: '{{ tmux_dir }}'
    dest: '$HOME/.config/tmux'
    force: true
    state: link

- name: Symlink tmux.conf
  file:
    src: '{{ tmux_dir }}/tmux.conf'
    dest: '$HOME/.tmux.conf'
    force: true
    state: link
